import { v4 as uuidv4 } from 'uuid'

export const testData = [
  {
    id: uuidv4(),
    question: 'Data_1',
    answer: 1,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_2',
    answer: 2,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_3',
    answer: 3,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_4',
    answer: 4,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_5',
    answer: 5,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_6',
    answer: 6,
    garde: 2,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_7',
    answer: 7,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_8',
    answer: 8,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_9',
    answer: 9,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_10',
    answer: 9,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_11',
    answer: 9,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_12',
    answer: 9,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_13',
    answer: 9,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
  {
    id: uuidv4(),
    question: 'Data_14',
    answer: 9,
    garde: 5,
    updated: '2023-07-15',
    createdBy: 'User user',
    editable: true,
  },
]
